const teamInfo = [
	{
		name: "Aden Lung",
		grade: "Senior",
		department: "Software",
		description: "I like to code :)",
		img: require("../assets/cad1.png"),
	},
	{
		name: "Aryan Mehrotra",
		grade: "Junior",
		department: "Software",
		description:
			"I’m Indian and I joined robotics because I wanna learn more about robots and how the code is worked and how each thing inside of the robot work together",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
	{
		name: "cad1",
		grade: "",
		department: "",
		description: "",
		img: require("../assets/cad1.png"),
	},
];

module.exports = {teamInfo};